application: waterlol-dev
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  expiration: "7d"
  static_dir: static

- url: /canvas-test
  static_dir: canvas-test

- url: /addTemplate
  script: landing.py

- url:  /.*
  script: landing.py 

- url: /m*
  script: landing.py
